name 'motd-rhel'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motd-rhel'
long_description 'Installs/Configures motd-rhel'
version '0.1.0'
